// <auto-generated />
using System;
using GestorMat.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorMat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421043625_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorMat.Domain.Entidades.Deposito", b =>
                {
                    b.Property<int>("Id_Deposito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Deposito"));

                    b.Property<string>("CodigoDeposito")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id_Deposito");

                    b.ToTable("depositos", (string)null);
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.Material", b =>
                {
                    b.Property<int>("Id_Material")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Material"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoMaterial")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Id_UnidadMedida")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("PermiteStockNegativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("StockMinimo")
                        .HasColumnType("float");

                    b.HasKey("Id_Material");

                    b.HasIndex("Id_UnidadMedida");

                    b.ToTable("materiales", (string)null);
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.MovimientoMaterial", b =>
                {
                    b.Property<int>("Id_MovimientoMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_MovimientoMaterial"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<string>("CodigoMovimiento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_DepositoDestino")
                        .HasColumnType("int");

                    b.Property<int>("Id_DepositoOrigen")
                        .HasColumnType("int");

                    b.Property<int>("Id_Material")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_MovimientoMaterial");

                    b.ToTable("MovimientosMaterial");
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<bool>("AccesoTotal")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Rol");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.Saldo", b =>
                {
                    b.Property<int>("Id_Saldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Saldo"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Deposito")
                        .HasColumnType("int");

                    b.Property<int>("Id_Material")
                        .HasColumnType("int");

                    b.HasKey("Id_Saldo");

                    b.HasIndex("Id_Deposito");

                    b.HasIndex("Id_Material", "Id_Deposito")
                        .IsUnique();

                    b.ToTable("saldos", (string)null);
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.UnidadMedida", b =>
                {
                    b.Property<int>("Id_UnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_UnidadMedida"));

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id_UnidadMedida");

                    b.ToTable("unidades_medida", (string)null);
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.Material", b =>
                {
                    b.HasOne("GestorMat.Domain.Entidades.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("Id_UnidadMedida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.Saldo", b =>
                {
                    b.HasOne("GestorMat.Domain.Entidades.Deposito", "Deposito")
                        .WithMany()
                        .HasForeignKey("Id_Deposito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorMat.Domain.Entidades.Material", "Material")
                        .WithMany()
                        .HasForeignKey("Id_Material")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposito");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("GestorMat.Domain.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestorMat.Domain.Entidades.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
